apiVersion: apps/v1  
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: chinmay334/demo-app:v20250109115544
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
          path: /
          ports: 5000
          readinessProbe:
            httpGet:
              path: /
              ports: 5000