name: Test, Build, and Deploy (Minikube)

on:
  push:
    branches:
      - master
    paths:
      - '**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

    # Setup Python Environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

    # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

    # Linting
      - name: Run Linting Tests
        run: |
          flake8 --ignore=E501,F401 .

    # Setup Minikube Docker Environment
      - name: Setup Minikube Docker
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          minikube start
          eval $(minikube docker-env)
      
    # Build Docker Image Inside Minikube
      - name: Build Docker Image
        run: |
          docker build . -t demo-app:latest
          docker images

    # Update Kubernetes Manifests
      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: .*|image: demo-app:latest|g" deploy/deploy.yaml
          cat deploy/deploy.yaml

    # Apply Kubernetes Manifests
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy/deploy.yaml
          kubectl apply -f svc.yaml
          kubectl get svc
